### ISSUE TITLE
Modmanager link is dead

### ISSUE THREAD

**Issue by nockstarr** [nihlen/bf2-docker#2]
Modmanager link is now dead..   
Tested the one from github but what ever version that really is does not work..  
https://github.com/L2KSolkov/modmanager/archive/master.zip  

I was not able to find a working link so I suggest upload a working version to this repo and include the license? I still have a copy of modmanager from the original link used in assets.txt.  
https://github.com/L2KSolkov/modmanager/blob/master/mm_licence.txt

**Comment by nihlen** [comment]
After checking the ModManager license (The Artistic License 1.0) I've included it in the repo instead.

The enhanced and enhanced-bf2cc branches should be updated so you can test again.
